create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.viandas (
  id bigint generated by default as identity primary key,
  nombre text not null unique,
  descripcion text,
  imagen text,
  categoria text,
  costo numeric(12, 2) not null default 0 check (costo >= 0),
  precio_venta numeric(12, 2) not null default 0 check (precio_venta >= 0),
  stock integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.pedidos (
  id bigint generated by default as identity primary key,
  cliente text not null,
  telefono text,
  direccion text,
  notas text,
  estado text not null default 'pendiente' check (estado in ('pendiente', 'en_proceso', 'listo', 'entregado', 'cancelado')),
  fecha_entrega timestamptz,
  entregado_at timestamptz,
  total_venta numeric(12, 2) not null default 0 check (total_venta >= 0),
  total_costo numeric(12, 2) not null default 0 check (total_costo >= 0),
  ganancia numeric(12, 2) not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.pedido_items (
  id bigint generated by default as identity primary key,
  pedido_id bigint not null references public.pedidos(id) on delete cascade,
  vianda_id bigint not null references public.viandas(id) on delete restrict,
  cantidad integer not null check (cantidad > 0),
  precio_unitario numeric(12, 2) not null check (precio_unitario >= 0),
  costo_unitario numeric(12, 2) not null check (costo_unitario >= 0),
  created_at timestamptz not null default now()
);

create table if not exists public.movimientos_stock (
  id bigint generated by default as identity primary key,
  vianda_id bigint not null references public.viandas(id) on delete restrict,
  tipo text not null check (tipo in ('entrada', 'salida', 'ajuste')),
  cantidad integer not null check (cantidad > 0),
  motivo text,
  referencia text,
  created_at timestamptz not null default now()
);

create index if not exists idx_pedidos_estado on public.pedidos(estado);
create index if not exists idx_pedidos_fecha_entrega on public.pedidos(fecha_entrega);
create index if not exists idx_pedidos_created_at on public.pedidos(created_at desc);
create index if not exists idx_pedido_items_pedido_id on public.pedido_items(pedido_id);
create index if not exists idx_pedido_items_vianda_id on public.pedido_items(vianda_id);
create index if not exists idx_movimientos_vianda_id on public.movimientos_stock(vianda_id);
create index if not exists idx_movimientos_created_at on public.movimientos_stock(created_at desc);

drop trigger if exists trg_viandas_updated_at on public.viandas;
create trigger trg_viandas_updated_at
before update on public.viandas
for each row
execute function public.set_updated_at();

drop trigger if exists trg_pedidos_updated_at on public.pedidos;
create trigger trg_pedidos_updated_at
before update on public.pedidos
for each row
execute function public.set_updated_at();
